### PR TITLE
Metflix : Display liked

### PR DESCRIPTION
**Pull request by arnoldnekemiah**
Hello @Zilola-Nazarova ,

- In this branch, I created a module for getting likes from the api, the file name is `get-liked.js`

- I then used the results of this function to display the likes on the liked movie.

- I have also added basic styling to make the homepage look nice.

- The number of likes being displayed is for the number of times you have liked wholly on the page, I am going to pin down exact likes in the next branch when I use the counter.

image

### CODE REVIEW

**Comment by Zilola-Nazarova** [comment]
Hi @arnoldnekemiah 👋🏻 
I'm currently reviewing this PR.
The data is successfully sent and received from 2 APIs.
But on my side, the likes are not displaying correctly. I thought we are supposed to show the number of likes for each movie (e.g. the first movie has 1 like and the second movie has 3 likes).
I need some time to examine the code and come up with a possible solution that might help to improve the code.

**Comment by arnoldnekemiah** [comment]
its what am working on alongside the counter

**Comment by Zilola-Nazarova** [comment]
Ah ok!
So maybe I'll approve this PR and then I'll review this feature closely in the next PR?

**Comment by arnoldnekemiah** [comment]
yes

**Review by Zilola-Nazarova — APPROVED** [review]
It is approved! It's time to merge it!
And by the way, I like the page styling. The layout is improved and the cards are looking much better 👍🏻

**Pull request merged**
